module.exports = {
  INITIAL_POSTS: 'INITIAL_POSTS',
  GLOBAL_POSTS: 'GLOBAL_POSTS',
  ERROR: 'ERROR',
  USER_CONNECTED: 'USER_CONNECTED',
  MESSAGE_RECEIVED: ' MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  USER_DICONNECTED: 'USER_DICONNECTED',
  TYPING: 'TYPING',
  VERIFY_USER: 'VERIFY_USER',
  LOGOUT: 'LOGOUT'
};
